from abc import ABC
from abc import abstractmethod
from types import SimpleNamespace

DATATYPES = SimpleNamespace(**
    {
        "NONE"     : 0,
        "INTAN"    : 1,
        "SMR"      : 3, # SMR support is really bad. Like, really, really bad, use at own peril.
        "MED"      : 4, # Binary files for/from Multimed; Primary naming convention
        "MULTIMED" : 4  # Binary files for/from Multimed; Secondary naming convention just in case I forget
        "MCSH5"    : 2, # H5 files generated by MCS tools
        "BIN"      : 4, # Binary files / raw files (default : 64ch / 16b / 10kHz)
    }
)

def recognize(file_path):
    if not(file_path):
        raise Exception("No file specified.")
    # TODO : recognize by header where possible
    i_extension = file_path.rfind(".")
    extension = file_path[i_extension:]
    if extension == ".rhd":
        return DATATYPES.INTAN
    elif extension == ".mcd":
        raise Exception("*.mcd files need to be converted to *.h5 format.")
    elif extension == ".h5":
        return DATATYPES.MCSH5
    elif extension == ".smr":
        return DATATYPES.SMR
    elif extension == ".bin":
        return DATATYPES.BIN
    else:
        raise Exception("Could not recognize data type from specified file.")

def DataSource(path, import_parameters=None):
    filetype = recognize(path)
    if filetype == DATATYPES.INTAN:
        from .intan.intan_datamanager import IntanDataSource
        return IntanDataSource(path=path, import_parameters=import_parameters)
    if filetype == DATATYPES.MCSH5:
        from .mcs.mcsh5_datamanager import H5DataSource
        return H5DataSource(path=path, import_parameters=import_parameters)
    if filetype == DATATYPES.BIN:
        from .bin.bin_datamanager import BinDataSource
        return BinDataSource(path=path, import_parameters=import_parameters)
    raise Exception("Unsupported format")

class AbstractDataSource(ABC):
    def __init__(self, path, import_parameters=None):
        self.file_path = path
        self.type = recognize(path)
        self._checkDatatype()
        self.data = None
        self._set_default_parameters()
        if import_parameters is not None:
            self.setImportParameters(import_parameters)
    # Load/unload methods
    @abstractmethod
    def load(self):
        pass
    @abstractmethod
    def load_one_channel(self):
        pass
    def unload(self):
        del self.data
    # Signal-related methods
    @abstractmethod
    def getFs(self):
        pass
    def getSignal(self, ch, bounds=None, bounds_s=None, bounds_samples=None):
        bounds = self._checkSignalBounds(bounds, bounds_s, bounds_samples)
        i      = self._checkRequestedChannel(ch)
        self._checkDatatype()
        self._checkDataLoaded()
        signal = self._getSignal_formatspecific(i)
        signal = self._applyBlanking(signal)
        signal = self._applyBounds(signal, bounds_samples=bounds)
        return signal
    # Channel-related methods
    def translateChannel(self, chname):
        """ Translates channel name (str) to the channel index (int) as used in the loaded data structure """
        self._checkDatatype()
        self._checkDataLoaded()
        allchannels = self.getChannels()
        allchannels = [str(c) for c in allchannels]
        if chname not in allchannels:
            raise Exception(f"Requested channel not in channel list : {allchannels}")
        return allchannels.index(chname)
    @abstractmethod
    def getChannels(self):
        pass
    def getAllChannels(self): 
        # Legacy method
        print("getAllChannels is deprecated. Use getChannels instead")
        return self.getChannels()
    def getAvailableChannels(self): 
        # Legacy method
        print("getAvailableChannels is deprecated. Use getChannels instead")
        return self.getChannels()
    # Internal methods
    def setImportParameters(self, parameters):
        for k in parameters:
            self.import_parameters[k] = parameters[k]
    @abstractmethod
    def _getSignal_formatspecific(self, i):
        """ This is the "format specific" part of the getSignal method : retrieve signal of channel i here """
        pass
    def _set_default_parameters(self):
        self.import_parameters = {}
        self.import_parameters["blank"] = [] # Should be a list of tuples of format (blank_start, blank_end), in seconds
        self.import_parameters["blank_value"] = 0
        self._set_default_parameters_formatspecific()
    @abstractmethod
    def _set_default_parameters_formatspecific(self):
        pass
    def _checkRequestedChannel(self, ch):
        if type(ch) is int:
            return ch
        if type(ch) is str:
            return self.translateChannel(ch)
    def _checkDatatype(self):
        if self.type is DATATYPES.NONE:
            raise Exception("DataSource : Unrecognized type.")
    def _checkDataLoaded(self, force_load=False):
        if not(self.data):
            if force_load:
                self.load()
            else:
                raise Exception("Datasource : Data not loaded.")
    def _checkSignalBounds(self, bounds, bounds_s, bounds_samples):
        # Legacy function : processes signal bounds in either the old format (only samples) 
        # or the new (either seconds or samples), and returns them in the new format (samples)
        #   * bounds         : bounds provided in samples (old format)
        #   * bounds_s       : bounds provided in seconds (new format), relies on proper definition of sampling frequency
        #   * bounds_samples : bounds provided in samples (new format)
        # All bounds provided should be a tuple (beginning, end)
        # Only one set of bounds should be provided
        if not(bounds) and not(bounds_s) and not(bounds_samples):
            # If no bounds provided, nothing to do
            bounds_samples = None
        elif bounds and not(bounds_s) and not(bounds_samples):
            # If only bounds in provided, its acts as samples
            bounds_samples = bounds
        elif not(bounds) and bounds_s and not(bounds_samples):
            # If only bounds_s in provided, convert to samples
            bounds_samples = (int(bounds_s[0] * self.getFs()), int(bounds_s[1] * self.getFs()))
        elif not(bounds) and not(bounds_s) and bounds_samples:
            # If only bounds_samples in provided, keep as is
            bounds_samples = bounds_samples
        else:
            # Cannot interpret several bounds definitions simultaneously
            raise Exception("Invalid bounds definition in getSignal")
        return bounds_samples
    def _applyBlanking(self, signal):
        for (blank_start, blank_end) in self.import_parameters["blank"]:
            i0 = int(blank_start * self.Fs)
            i1 = int(blank_end   * self.Fs)
            signal[i0:i1] = self.import_parameters["blank_value"]
        return signal
    def _applyBounds(self, signal, bounds_samples=None):
        return signal if not bounds_samples else signal[bounds_samples[0]:bounds_samples[1]]

    def __getitem__(self, ch):
        return self.getSignal(ch)

    @property
    def channels(self):
        return self.getChannels()
    @property
    def Fs(self):
        return self.getFs()
